services:
  frontend:
    build:
      context: /home/denis/Dokumente/SYP/Fork-github/2324-4bhif-syp-project-iot-dashboard/frontend
      dockerfile: docker/Dockerfile
    image: leoenergy-kiosk:local
    container_name: leoenergy-kiosk
    ports:
      - "8000:80"
    depends_on:
      - influxdb
      - grafana
      - leoenergy
