INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('1', 'undefined', 'U01', 'Hall (Basement)', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('2', 'undefined', 'U02', 'Hallway (Left)', 'West');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('183', 'undefined', 'U02', 'Hallway (Up)', 'North');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('3', 'undefined', 'U03', 'Storage Room', 'North');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('4', 'BioLab', 'U04', 'Laboratory', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('5', 'BioLab', 'U04B', 'Laboratory', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('6', 'undefined', 'U05', 'Storage', 'East');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('7', 'undefined', 'U07', 'Plastics', 'West');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('8', 'undefined', 'U08', 'Telecommunications', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('9', 'undefined', 'U08A', 'Computer Network Technology', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('10', 'undefined', 'U08B', 'Network Technology', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('11', 'undefined', 'U10', 'IT Room', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('12', 'undefined', 'U11', 'Teachers Restroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('13', 'undefined', 'U14', 'Womens Restroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('14', 'undefined', 'U16', 'Disabled Restroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('15', 'undefined', 'U26', 'Shelter', 'South');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('16', 'undefined', 'U39', 'Hallway (Up)', 'North');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('184', 'undefined', 'U39', 'Hallway (Left)', 'West');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('17', 'undefined', 'U41', 'Shelter', 'East');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('18', 'undefined', 'U58', 'Changing Room', 'West');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('19', 'undefined', 'U66', 'Women?s Restroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('20', 'undefined', 'U64', 'Men?s Restroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('21', 'undefined', 'U70', 'Radio Station', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('22', 'undefined', 'U71', 'High Frequency', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('23', 'undefined', 'U72', 'Technical Informatics', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('24', 'undefined', 'U73', 'Control Technology', 'North');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('25', 'undefined', 'U74', 'Electrical Device Manufacturing', 'South');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('26', 'undefined', 'U77', 'HF Technology', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('27', 'undefined', 'U78', 'Print Manufacturing', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('28', 'undefined', 'U79', 'Welding', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('29', 'undefined', 'U81', 'Control Engineering', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('30', 'undefined', 'U82A', 'Computer Room1', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('31', 'undefined', 'U82B', 'Computer Room2', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('32', 'undefined', 'U83', 'Low-Frequency Technology', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('33', 'undefined', 'U84A', 'Electrical Installation', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('34', 'undefined', 'U84B', 'Basic Electrical Training', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('35', 'undefined', 'U85', 'Electronics B', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('36', 'undefined', 'U86A', 'Work Preparation', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('37', 'undefined', 'U86B', 'Programming', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('38', 'undefined', 'U87', 'Precision Engineering', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('39', 'undefined', 'U88', 'Mechanics', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('40', 'undefined', 'U89', 'Basic Mechanical Training', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('41', 'undefined', 'U90', 'Magazine', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('42', 'undefined', 'U91', 'Workshop Manager', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('43', 'undefined', 'U92', 'Teachers Lounge', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('46', 'undefined', 'E02', 'Hall (Ground Floor)', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('47', 'undefined', 'E03', 'School Caretaker', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('48', 'undefined', 'E04', 'Hallway (Left)', 'West');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('185', 'undefined', 'E04', 'Hallway (Down)', 'South');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('49', 'undefined', 'E05', 'Teachers Lounge', 'North');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('50', 'undefined', 'E06', 'Teachers Lounge', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('51', 'Marie Curie', 'E07', 'Chemistry Room', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('52', 'undefined', 'E08', 'Teachers Lounge', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('53', 'Lise Meitner', 'E09', 'Physics Room', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('54', 'undefined', 'E10', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('55', 'undefined', 'E11', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('56', 'undefined', 'E13', 'Men?s Restroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('57', 'undefined', 'E16', 'Teachers? Restroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('58', 'undefined', 'E18', 'Disabled Restroom', 'South');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('59', 'undefined', 'E19', 'Cleaning Closet', 'West');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('60', 'undefined', 'E20', 'Women?s Restroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('61', 'undefined', 'E22', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('62', 'undefined', 'E23', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('63', 'undefined', 'E24', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('64', 'undefined', 'E25', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('65', 'undefined', 'E26', 'Classroom', 'East');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('66', 'undefined', 'E30', 'Hallway (Up)', 'North');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('186', 'undefined', 'E30', 'Hallway (right)', 'East');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('67', 'undefined', 'E31', 'Teachers Lounge', 'West');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('68', 'undefined', 'E32', 'Teachers Lounge', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('69', 'undefined', 'E33', 'Recreation Room', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('70', 'undefined', 'E35', 'Administration Office', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('71', 'undefined', 'E36', 'Administration Office', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('72', 'undefined', 'E37', 'Principal', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('73', 'Johannes Kepler', 'E38+39', 'Administration Office', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('77', 'undefined', 'E43', 'Teachers Restroom', 'East');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('78', 'undefined', 'E45+46', 'Disabled Restroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('79', 'undefined', 'E50', 'Teachers Lounge', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('80', 'undefined', 'E51', 'Teachers Lounge', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('81', 'undefined', 'E52', 'Department Head (IT)', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('82', 'undefined', 'E53+54', 'Teachers Lounge', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('83', 'undefined', 'E55', 'Department Head (ET)', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('84', 'undefined', 'E56', 'Storage Room', 'South');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('85', 'undefined', 'E57', 'Canteen', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('86', 'Edsger Dijkstra', 'E58-1', 'IT Room 11', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('87', 'undefined', 'E58-2', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('88', 'undefined', 'E59', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('89', 'undefined', 'E60', 'Men?s Restroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('90', 'undefined', 'E62', 'Women?s Restroom', 'North');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('91', 'undefined', 'E71', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('92', 'undefined', 'E72', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('93', 'Margaret Hamilton', 'E73-a', 'IT Room 7', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('94', 'undefined', 'E74', 'Teachers Lounge', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('95', 'undefined', 'T1', 'Hallway (Gyms)', 'East');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('96', 'undefined', 'T2', 'School Doctor', 'North');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('97', 'undefined', 'T05', 'Old HTL Gym', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('98', 'undefined', 'T10', 'New HTL Gym', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('99', 'undefined', 'T18', 'Storage', 'South');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('100', 'undefined', 'T21', 'Storage', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('102', 'undefined', '101', 'Hall (1st Floor)', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('103', 'undefined', '102', 'Hallway (left)', 'West');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('187', 'undefined', '102', 'Hallway (down)', 'South');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('104', 'undefined', '103', 'Teachers Lounge', 'North');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('105', 'undefined', '104', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('106', 'undefined', '105', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('107', 'undefined', '106', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('108', 'undefined', '107', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('109', 'Ada Lovelace', '108-a', 'IT Room 2', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('110', 'Don Knuth', '109-a', 'IT Room 1', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('111', 'undefined', '110', 'Men?s Restroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('112', 'undefined', '114', 'Teachers? Restroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('113', 'undefined', '115', 'Disabled Restroom', 'South');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('114', 'undefined', '116', 'Cleaning Closet', 'West');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('115', 'undefined', '118', 'Women?s Restroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('116', 'undefined', '119', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('117', 'undefined', '120', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('118', 'Niklaus Wirth', '121', 'IT Room3', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('119', 'Grace Hopper', '122', 'IT Room 4', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('120', 'Brian Kernighan', '123', 'IT Room 5', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('121', 'undefined', '124', 'System Administration', 'East');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('122', 'undefined', '130', 'Hallway (up)', 'North');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('188', 'undefined', '130', 'Hallway(right)', 'East');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('123', 'undefined', '131', 'Sound Room', 'South');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('124', 'undefined', '132', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('125', 'undefined', '133', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('126', 'undefined', '134', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('127', 'Barbara Liskov', '135', 'IT Room 10', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('128', 'undefined', '136', 'Men?s Restroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('129', 'undefined', '138', 'Cleaning Closet', 'North');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('130', 'undefined', '139', 'Teachers Restroom', 'East');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('131', 'undefined', '140', 'Womens Restroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('132', 'undefined', '142', 'Teachers Lounge', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('133', 'undefined', '143a', 'IT Room', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('134', 'undefined', '143b', 'IT Room', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('135', 'undefined', '144', 'IT Room', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('136', 'undefined', '145', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('137', 'undefined', '146', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('138', 'undefined', '147', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('139', 'undefined', '148', 'Teachers Lounge', 'West');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('140', 'undefined', '151', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('141', 'undefined', '152', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('142', 'undefined', '153', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('143', 'undefined', '154', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('145', 'undefined', '201', 'Hall (2nd Floor)', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('146', 'undefined', '202', 'Hallway (left)', 'West');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('189', 'undefined', '202', 'Hallway (down)', 'South');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('147', 'undefined', '203', 'Teachers Lounge', 'North');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('148', 'undefined', '204', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('149', 'undefined', '205', 'Teachers Lounge', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('150', 'undefined', '206', 'Teachers Lounge', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('151', 'undefined', '208', 'Teachers Restroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('152', 'undefined', '209', 'Men?s Restroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('153', 'undefined', '212', 'Women?s Restroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('154', 'undefined', '213', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('155', 'undefined', '214', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('156', 'undefined', '215', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('157', 'undefined', '216', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('158', 'undefined', '217', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('159', 'undefined', '218', 'Teachers Lounge', 'East');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('160', 'undefined', '220', 'Teachers Lounge', 'East');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('161', 'undefined', '221', 'Teachers Lounge', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('162', 'undefined', '222', 'Teachers Lounge', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('163', 'undefined', '223', 'Teachers Lounge', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('164', 'undefined', '224', 'Teachers Lounge', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('165', 'undefined', '225', 'Hallway (up)', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('190', 'undefined', '225', 'Hallway (right)', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('166', 'undefined', '226', 'Teachers Lounge', 'South');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('167', 'undefined', '227', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('168', 'undefined', '228', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('169', 'undefined', '229', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('170', 'undefined', '230', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('171', 'undefined', '231', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('172', 'undefined', '232', 'Men?s Restroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('173', 'undefined', '236', 'Women?s Restroom', 'North');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('174', 'undefined', '237', 'Teachers Lounge', 'North');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('175', 'undefined', '238', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('176', 'undefined', '239', 'Study Group Room', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('177', 'undefined', '240', 'Small Chamber', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('178', 'undefined', '241', 'Teachers Lounge', 'West');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('179', 'undefined', '251', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('180', 'undefined', '252', 'Classroom', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('181', 'Steve Wozniak', '253-a', 'IT Room 8', 'NULL');
INSERT INTO room (RoomId, RoomLabel, RoomName, RoomType, Direction) VALUES ('182', 'undefined', '254', 'Teachers Lounge', 'NULL');

commit;

UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = 3 WHERE RoomId = 1;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = NULL WHERE RoomId = 2;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = NULL WHERE RoomId = 183;
UPDATE room SET Corridor = 2, NeighbourInside = 1, NeighbourOutside = 4 WHERE RoomId = 3;
UPDATE room SET Corridor = 2, NeighbourInside = 3, NeighbourOutside = 5 WHERE RoomId = 4;
UPDATE room SET Corridor = 2, NeighbourInside = 4, NeighbourOutside = 6 WHERE RoomId = 5;
UPDATE room SET Corridor = 183, NeighbourInside = 5, NeighbourOutside = 41 WHERE RoomId = 6;
UPDATE room SET Corridor = 183, NeighbourInside = NULL, NeighbourOutside = 40 WHERE RoomId = 7;
UPDATE room SET Corridor = 2, NeighbourInside = 11, NeighbourOutside = 9 WHERE RoomId = 8;
UPDATE room SET Corridor = 2, NeighbourInside = 8, NeighbourOutside = 10 WHERE RoomId = 9;
UPDATE room SET Corridor = 2, NeighbourInside = 9, NeighbourOutside = NULL WHERE RoomId = 10;
UPDATE room SET Corridor = 2, NeighbourInside = 12, NeighbourOutside = 8 WHERE RoomId = 11;
UPDATE room SET Corridor = 2, NeighbourInside = 13, NeighbourOutside = 11 WHERE RoomId = 12;
UPDATE room SET Corridor = 2, NeighbourInside = 14, NeighbourOutside = 12 WHERE RoomId = 13;
UPDATE room SET Corridor = 2, NeighbourInside = 15, NeighbourOutside = 13 WHERE RoomId = 14;
UPDATE room SET Corridor = 2, NeighbourInside = 1, NeighbourOutside = 14 WHERE RoomId = 15;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = NULL WHERE RoomId = 16;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = NULL WHERE RoomId = 184;
UPDATE room SET Corridor = 16, NeighbourInside = 1, NeighbourOutside = 19 WHERE RoomId = 17;
UPDATE room SET Corridor = 16, NeighbourInside = 1, NeighbourOutside = 25 WHERE RoomId = 18;
UPDATE room SET Corridor = 16, NeighbourInside = 17, NeighbourOutside = 20 WHERE RoomId = 19;
UPDATE room SET Corridor = 16, NeighbourInside = 19, NeighbourOutside = 21 WHERE RoomId = 20;
UPDATE room SET Corridor = 16, NeighbourInside = 20, NeighbourOutside = 21 WHERE RoomId = 21;
UPDATE room SET Corridor = 16, NeighbourInside = 21, NeighbourOutside = 22 WHERE RoomId = 22;
UPDATE room SET Corridor = 16, NeighbourInside = 22, NeighbourOutside = NULL WHERE RoomId = 23;
UPDATE room SET Corridor = 184, NeighbourInside = 29, NeighbourOutside = NULL WHERE RoomId = 24;
UPDATE room SET Corridor = 184, NeighbourInside = 18, NeighbourOutside = 26 WHERE RoomId = 25;
UPDATE room SET Corridor = 184, NeighbourInside = 27, NeighbourOutside = 25 WHERE RoomId = 26;
UPDATE room SET Corridor = 184, NeighbourInside = 28, NeighbourOutside = 26 WHERE RoomId = 27;
UPDATE room SET Corridor = 184, NeighbourInside = NULL, NeighbourOutside = 27 WHERE RoomId = 28;
UPDATE room SET Corridor = 184, NeighbourInside = 30, NeighbourOutside = 24 WHERE RoomId = 29;
UPDATE room SET Corridor = 184, NeighbourInside = 31, NeighbourOutside = 29 WHERE RoomId = 30;
UPDATE room SET Corridor = 184, NeighbourInside = 32, NeighbourOutside = 30 WHERE RoomId = 31;
UPDATE room SET Corridor = 184, NeighbourInside = 33, NeighbourOutside = 31 WHERE RoomId = 32;
UPDATE room SET Corridor = 184, NeighbourInside = 34, NeighbourOutside = 32 WHERE RoomId = 33;
UPDATE room SET Corridor = 184, NeighbourInside = 35, NeighbourOutside = 33 WHERE RoomId = 34;
UPDATE room SET Corridor = 184, NeighbourInside = 36, NeighbourOutside = 34 WHERE RoomId = 35;
UPDATE room SET Corridor = 184, NeighbourInside = 37, NeighbourOutside = 35 WHERE RoomId = 36;
UPDATE room SET Corridor = 184, NeighbourInside = 38, NeighbourOutside = 36 WHERE RoomId = 37;
UPDATE room SET Corridor = 183, NeighbourInside = NULL, NeighbourOutside = 39 WHERE RoomId = 38;
UPDATE room SET Corridor = 183, NeighbourInside = 38, NeighbourOutside = 40 WHERE RoomId = 39;
UPDATE room SET Corridor = 183, NeighbourInside = 39, NeighbourOutside = 7 WHERE RoomId = 40;
UPDATE room SET Corridor = 183, NeighbourInside = 42, NeighbourOutside = 6 WHERE RoomId = 41;
UPDATE room SET Corridor = 183, NeighbourInside = 43, NeighbourOutside = 41 WHERE RoomId = 42;
UPDATE room SET Corridor = 183, NeighbourInside = NULL, NeighbourOutside = 42 WHERE RoomId = 43;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = 49 WHERE RoomId = 46;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = 46 WHERE RoomId = 47;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = NULL WHERE RoomId = 48;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = NULL WHERE RoomId = 185;
UPDATE room SET Corridor = 48, NeighbourInside = 46, NeighbourOutside = 50 WHERE RoomId = 49;
UPDATE room SET Corridor = 48, NeighbourInside = 49, NeighbourOutside = 51 WHERE RoomId = 50;
UPDATE room SET Corridor = 48, NeighbourInside = 50, NeighbourOutside = 52 WHERE RoomId = 51;
UPDATE room SET Corridor = 48, NeighbourInside = 51, NeighbourOutside = 53 WHERE RoomId = 52;
UPDATE room SET Corridor = 48, NeighbourInside = 52, NeighbourOutside = NULL WHERE RoomId = 53;
UPDATE room SET Corridor = 48, NeighbourInside = NULL, NeighbourOutside = 55 WHERE RoomId = 54;
UPDATE room SET Corridor = 48, NeighbourInside = 54, NeighbourOutside = 56 WHERE RoomId = 55;
UPDATE room SET Corridor = 48, NeighbourInside = 55, NeighbourOutside = 57 WHERE RoomId = 56;
UPDATE room SET Corridor = 48, NeighbourInside = 56, NeighbourOutside = 58 WHERE RoomId = 57;
UPDATE room SET Corridor = 48, NeighbourInside = 57, NeighbourOutside = NULL WHERE RoomId = 58;
UPDATE room SET Corridor = 185, NeighbourInside = NULL, NeighbourOutside = 60 WHERE RoomId = 59;
UPDATE room SET Corridor = 185, NeighbourInside = 59, NeighbourOutside = 61 WHERE RoomId = 60;
UPDATE room SET Corridor = 185, NeighbourInside = 60, NeighbourOutside = 61 WHERE RoomId = 61;
UPDATE room SET Corridor = 185, NeighbourInside = 60, NeighbourOutside = 94 WHERE RoomId = 62;
UPDATE room SET Corridor = 185, NeighbourInside = 64, NeighbourOutside = 91 WHERE RoomId = 63;
UPDATE room SET Corridor = 185, NeighbourInside = 65, NeighbourOutside = 62 WHERE RoomId = 64;
UPDATE room SET Corridor = 185, NeighbourInside = NULL, NeighbourOutside = 63 WHERE RoomId = 65;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = NULL WHERE RoomId = 66;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = NULL WHERE RoomId = 186;
UPDATE room SET Corridor = 66, NeighbourInside = 46, NeighbourOutside = 68 WHERE RoomId = 67;
UPDATE room SET Corridor = 66, NeighbourInside = 67, NeighbourOutside = 69 WHERE RoomId = 68;
UPDATE room SET Corridor = 66, NeighbourInside = 68, NeighbourOutside = 70 WHERE RoomId = 69;
UPDATE room SET Corridor = 66, NeighbourInside = 69, NeighbourOutside = 71 WHERE RoomId = 70;
UPDATE room SET Corridor = 66, NeighbourInside = 70, NeighbourOutside = 72 WHERE RoomId = 71;
UPDATE room SET Corridor = 66, NeighbourInside = 71, NeighbourOutside = 73 WHERE RoomId = 72;
UPDATE room SET Corridor = 66, NeighbourInside = 72, NeighbourOutside = NULL WHERE RoomId = 73;
UPDATE room SET Corridor = 66, NeighbourInside = NULL, NeighbourOutside = 78 WHERE RoomId = 77;
UPDATE room SET Corridor = 66, NeighbourInside = 77, NeighbourOutside = 79 WHERE RoomId = 78;
UPDATE room SET Corridor = 66, NeighbourInside = 78, NeighbourOutside = 80 WHERE RoomId = 79;
UPDATE room SET Corridor = 66, NeighbourInside = 79, NeighbourOutside = 81 WHERE RoomId = 80;
UPDATE room SET Corridor = 66, NeighbourInside = 80, NeighbourOutside = 82 WHERE RoomId = 81;
UPDATE room SET Corridor = 66, NeighbourInside = 81, NeighbourOutside = 83 WHERE RoomId = 82;
UPDATE room SET Corridor = 66, NeighbourInside = 82, NeighbourOutside = NULL WHERE RoomId = 83;
UPDATE room SET Corridor = 186, NeighbourInside = NULL, NeighbourOutside = 85 WHERE RoomId = 84;
UPDATE room SET Corridor = 186, NeighbourInside = 84, NeighbourOutside = 86 WHERE RoomId = 85;
UPDATE room SET Corridor = 186, NeighbourInside = 85, NeighbourOutside = 87 WHERE RoomId = 86;
UPDATE room SET Corridor = 186, NeighbourInside = 86, NeighbourOutside = NULL WHERE RoomId = 87;
UPDATE room SET Corridor = 186, NeighbourInside = 89, NeighbourOutside = NULL WHERE RoomId = 88;
UPDATE room SET Corridor = 186, NeighbourInside = 90, NeighbourOutside = 88 WHERE RoomId = 89;
UPDATE room SET Corridor = 186, NeighbourInside = NULL, NeighbourOutside = 89 WHERE RoomId = 90;
UPDATE room SET Corridor = 48, NeighbourInside = 63, NeighbourOutside = 92 WHERE RoomId = 91;
UPDATE room SET Corridor = 48, NeighbourInside = 91, NeighbourOutside = NULL WHERE RoomId = 92;
UPDATE room SET Corridor = 48, NeighbourInside = 94, NeighbourOutside = NULL WHERE RoomId = 93;
UPDATE room SET Corridor = 48, NeighbourInside = 62, NeighbourOutside = 93 WHERE RoomId = 94;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = NULL WHERE RoomId = 95;
UPDATE room SET Corridor = 95, NeighbourInside = NULL, NeighbourOutside = 97 WHERE RoomId = 96;
UPDATE room SET Corridor = 95, NeighbourInside = 96, NeighbourOutside = 98 WHERE RoomId = 97;
UPDATE room SET Corridor = 95, NeighbourInside = 97, NeighbourOutside = NULL WHERE RoomId = 98;
UPDATE room SET Corridor = 95, NeighbourInside = NULL, NeighbourOutside = 100 WHERE RoomId = 99;
UPDATE room SET Corridor = 95, NeighbourInside = 99, NeighbourOutside = NULL WHERE RoomId = 100;
UPDATE room SET Corridor = NULL, NeighbourInside = 139, NeighbourOutside = 104 WHERE RoomId = 102;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = NULL WHERE RoomId = 103;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = NULL WHERE RoomId = 187;
UPDATE room SET Corridor = 103, NeighbourInside = 102, NeighbourOutside = 105 WHERE RoomId = 104;
UPDATE room SET Corridor = 103, NeighbourInside = 104, NeighbourOutside = 106 WHERE RoomId = 105;
UPDATE room SET Corridor = 103, NeighbourInside = 105, NeighbourOutside = 107 WHERE RoomId = 106;
UPDATE room SET Corridor = 103, NeighbourInside = 106, NeighbourOutside = 108 WHERE RoomId = 107;
UPDATE room SET Corridor = 103, NeighbourInside = 107, NeighbourOutside = NULL WHERE RoomId = 108;
UPDATE room SET Corridor = 103, NeighbourInside = 110, NeighbourOutside = NULL WHERE RoomId = 109;
UPDATE room SET Corridor = 103, NeighbourInside = 111, NeighbourOutside = 109 WHERE RoomId = 110;
UPDATE room SET Corridor = 103, NeighbourInside = 112, NeighbourOutside = 110 WHERE RoomId = 111;
UPDATE room SET Corridor = 103, NeighbourInside = 113, NeighbourOutside = 111 WHERE RoomId = 112;
UPDATE room SET Corridor = 103, NeighbourInside = NULL, NeighbourOutside = 112 WHERE RoomId = 113;
UPDATE room SET Corridor = 187, NeighbourInside = NULL, NeighbourOutside = 115 WHERE RoomId = 114;
UPDATE room SET Corridor = 187, NeighbourInside = 114, NeighbourOutside = 116 WHERE RoomId = 115;
UPDATE room SET Corridor = 187, NeighbourInside = 115, NeighbourOutside = 117 WHERE RoomId = 116;
UPDATE room SET Corridor = 187, NeighbourInside = 116, NeighbourOutside = 143 WHERE RoomId = 117;
UPDATE room SET Corridor = 187, NeighbourInside = 119, NeighbourOutside = 140 WHERE RoomId = 118;
UPDATE room SET Corridor = 187, NeighbourInside = 120, NeighbourOutside = 118 WHERE RoomId = 119;
UPDATE room SET Corridor = 187, NeighbourInside = 121, NeighbourOutside = 119 WHERE RoomId = 120;
UPDATE room SET Corridor = 187, NeighbourInside = 102, NeighbourOutside = 120 WHERE RoomId = 121;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = NULL WHERE RoomId = 122;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = NULL WHERE RoomId = 188;
UPDATE room SET Corridor = 188, NeighbourInside = 102, NeighbourOutside = 124 WHERE RoomId = 123;
UPDATE room SET Corridor = 188, NeighbourInside = 123, NeighbourOutside = 125 WHERE RoomId = 124;
UPDATE room SET Corridor = 188, NeighbourInside = 124, NeighbourOutside = 126 WHERE RoomId = 125;
UPDATE room SET Corridor = 188, NeighbourInside = 125, NeighbourOutside = NULL WHERE RoomId = 126;
UPDATE room SET Corridor = 188, NeighbourInside = 128, NeighbourOutside = NULL WHERE RoomId = 127;
UPDATE room SET Corridor = 188, NeighbourInside = 129, NeighbourOutside = 127 WHERE RoomId = 128;
UPDATE room SET Corridor = 188, NeighbourInside = NULL, NeighbourOutside = 128 WHERE RoomId = 129;
UPDATE room SET Corridor = 122, NeighbourInside = NULL, NeighbourOutside = 131 WHERE RoomId = 130;
UPDATE room SET Corridor = 122, NeighbourInside = 130, NeighbourOutside = 132 WHERE RoomId = 131;
UPDATE room SET Corridor = 122, NeighbourInside = 131, NeighbourOutside = 133 WHERE RoomId = 132;
UPDATE room SET Corridor = 122, NeighbourInside = 132, NeighbourOutside = 134 WHERE RoomId = 133;
UPDATE room SET Corridor = 122, NeighbourInside = 133, NeighbourOutside = NULL WHERE RoomId = 134;
UPDATE room SET Corridor = 122, NeighbourInside = 136, NeighbourOutside = NULL WHERE RoomId = 135;
UPDATE room SET Corridor = 122, NeighbourInside = 137, NeighbourOutside = 135 WHERE RoomId = 136;
UPDATE room SET Corridor = 122, NeighbourInside = 138, NeighbourOutside = 136 WHERE RoomId = 137;
UPDATE room SET Corridor = 122, NeighbourInside = 139, NeighbourOutside = 137 WHERE RoomId = 138;
UPDATE room SET Corridor = 122, NeighbourInside = 102, NeighbourOutside = 138 WHERE RoomId = 139;
UPDATE room SET Corridor = 187, NeighbourInside = 118, NeighbourOutside = 141 WHERE RoomId = 140;
UPDATE room SET Corridor = 187, NeighbourInside = 140, NeighbourOutside = NULL WHERE RoomId = 141;
UPDATE room SET Corridor = 187, NeighbourInside = 143, NeighbourOutside = NULL WHERE RoomId = 142;
UPDATE room SET Corridor = 187, NeighbourInside = 117, NeighbourOutside = 142 WHERE RoomId = 143;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = 147 WHERE RoomId = 145;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = NULL WHERE RoomId = 146;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = NULL WHERE RoomId = 189;
UPDATE room SET Corridor = 146, NeighbourInside = 145, NeighbourOutside = 148 WHERE RoomId = 147;
UPDATE room SET Corridor = 146, NeighbourInside = 147, NeighbourOutside = 149 WHERE RoomId = 148;
UPDATE room SET Corridor = 146, NeighbourInside = 148, NeighbourOutside = NULL WHERE RoomId = 149;
UPDATE room SET Corridor = 146, NeighbourInside = 148, NeighbourOutside = 151 WHERE RoomId = 150;
UPDATE room SET Corridor = 146, NeighbourInside = 150, NeighbourOutside = NULL WHERE RoomId = 151;
UPDATE room SET Corridor = 189, NeighbourInside = NULL, NeighbourOutside = 153 WHERE RoomId = 152;
UPDATE room SET Corridor = 189, NeighbourInside = 152, NeighbourOutside = 154 WHERE RoomId = 153;
UPDATE room SET Corridor = 189, NeighbourInside = 153, NeighbourOutside = 155 WHERE RoomId = 154;
UPDATE room SET Corridor = 189, NeighbourInside = 154, NeighbourOutside = 182 WHERE RoomId = 155;
UPDATE room SET Corridor = 189, NeighbourInside = 157, NeighbourOutside = 179 WHERE RoomId = 156;
UPDATE room SET Corridor = 189, NeighbourInside = 158, NeighbourOutside = 156 WHERE RoomId = 157;
UPDATE room SET Corridor = 189, NeighbourInside = 159, NeighbourOutside = 157 WHERE RoomId = 158;
UPDATE room SET Corridor = 189, NeighbourInside = 160, NeighbourOutside = 158 WHERE RoomId = 159;
UPDATE room SET Corridor = 145, NeighbourInside = 161, NeighbourOutside = 159 WHERE RoomId = 160;
UPDATE room SET Corridor = 145, NeighbourInside = 162, NeighbourOutside = 160 WHERE RoomId = 161;
UPDATE room SET Corridor = 145, NeighbourInside = 163, NeighbourOutside = 161 WHERE RoomId = 162;
UPDATE room SET Corridor = 145, NeighbourInside = 162, NeighbourOutside = 164 WHERE RoomId = 163;
UPDATE room SET Corridor = 145, NeighbourInside = 163, NeighbourOutside = 166 WHERE RoomId = 164;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = NULL WHERE RoomId = 165;
UPDATE room SET Corridor = NULL, NeighbourInside = NULL, NeighbourOutside = NULL WHERE RoomId = 190;
UPDATE room SET Corridor = 190, NeighbourInside = 164, NeighbourOutside = 167 WHERE RoomId = 166;
UPDATE room SET Corridor = 190, NeighbourInside = 166, NeighbourOutside = 168 WHERE RoomId = 167;
UPDATE room SET Corridor = 190, NeighbourInside = 167, NeighbourOutside = 169 WHERE RoomId = 168;
UPDATE room SET Corridor = 190, NeighbourInside = 168, NeighbourOutside = NULL WHERE RoomId = 169;
UPDATE room SET Corridor = 190, NeighbourInside = 171, NeighbourOutside = NULL WHERE RoomId = 170;
UPDATE room SET Corridor = 190, NeighbourInside = 172, NeighbourOutside = 170 WHERE RoomId = 171;
UPDATE room SET Corridor = 190, NeighbourInside = 173, NeighbourOutside = 171 WHERE RoomId = 172;
UPDATE room SET Corridor = 190, NeighbourInside = NULL, NeighbourOutside = 172 WHERE RoomId = 173;
UPDATE room SET Corridor = 165, NeighbourInside = 175, NeighbourOutside = NULL WHERE RoomId = 174;
UPDATE room SET Corridor = 165, NeighbourInside = 176, NeighbourOutside = 174 WHERE RoomId = 175;
UPDATE room SET Corridor = 165, NeighbourInside = 177, NeighbourOutside = 175 WHERE RoomId = 176;
UPDATE room SET Corridor = 165, NeighbourInside = 178, NeighbourOutside = 176 WHERE RoomId = 177;
UPDATE room SET Corridor = 165, NeighbourInside = 145, NeighbourOutside = 177 WHERE RoomId = 178;
UPDATE room SET Corridor = 146, NeighbourInside = 156, NeighbourOutside = 180 WHERE RoomId = 179;
UPDATE room SET Corridor = 146, NeighbourInside = 179, NeighbourOutside = NULL WHERE RoomId = 180;
UPDATE room SET Corridor = 146, NeighbourInside = 182, NeighbourOutside = NULL WHERE RoomId = 181;
UPDATE room SET Corridor = 146, NeighbourInside = 155, NeighbourOutside = 181 WHERE RoomId = 182;